### ISSUE TITLE
Add option to disable auto-extending of expiration with Get

### ISSUE THREAD

**Issue by sagarkrkv** [ReneKroon/ttlcache#12]
I'm planning to use this library as a backend for DNS caching in a proxy server. 

After the TTL expires, I plan to fetch a new and possibly updated value from the DNS server. The auto-extending of TTL with `Get()` will result in the cache never being updated and potentially having stale values.

**Comment by ReneKroon** [comment]
Released with 1.2.0

**Comment by jpmeijers** [comment]
How do one do this in V3?
