### ISSUE TITLE
Panic with SetCheckExpirationCallback

### ISSUE THREAD

**Issue by huangpeizhi2018** [ReneKroon/ttlcache#13]
hi, @ReneKroo

I have encountered some problems with ttlcache, I don't know why?
Can help solve this problem? 
thanks.

- The panic appears when this program runs below
`
func main() {
	cacheAD := ttlcache.NewCache()
	cacheAD.SetTTL(time.Second * time.Duration(5))
	cacheAD.SetCheckExpirationCallback(func(key string, value interface{}) bool {
		v := value.(*int)
		log.Printf("key=%v, value=%d\n", key, *v)
		return true
	})

	i := 2
	cacheAD.Set("a", &i)
	ch := make(chan struct{})
	<-ch
}
`
- Error message
`
2018/09/07 15:58:52 key=a, value=2
panic: runtime error: index out of range
goroutine 18 [running]:
github.com/ReneKroon/ttlcache.(*Cache).startExpirationProcessing(0xc04208c000)
        D:/workspace-go/busAnalyze/src/github.com/ReneKroon/ttlcache/cache.go:84 +0x4f8
created by github.com/ReneKroon/ttlcache.NewCache
        D:/workspace-go/busAnalyze/src/github.com/ReneKroon/ttlcache/cache.go:232 +0x11e
`

**Comment by huangpeizhi2018** [comment]
@ReneKroon ,
go1.10 windows/amd64

**Comment by huangpeizhi2018** [comment]
@ReneKroon , Sorry, the above is wrong, SetCheckExpirationCallback is return false.

**Comment by ReneKroon** [comment]
Thank you, i was able to fix this with latest commit.
