### ISSUE TITLE
checkExpireCallback doesn't work when skipTtlExtension is enabled.

### ISSUE THREAD

**Issue by sagarkrkv** [ReneKroon/ttlcache#15]
When checkExpireCallback returns true, we should always extend the `ttl` of the item, irrespective of the value of `skipTtlExtension`.
https://github.com/ReneKroon/ttlcache/blob/f76125ae8c0559130e32b4f47bb3284f7abed9a8/cache.go#L89-L93

**Comment by ReneKroon** [comment]
I appreciate the attached test case, since it crashes it's pretty obvious something is wrong .. I agree with your reasoning about extending TTL, so i will merge it.
