### ISSUE TITLE
expired behavior strange?

### ISSUE THREAD

**Issue by marcelloh** [ReneKroon/ttlcache#19]
I have the expirationCallback and an expire-time of 5 seconds
Let's say I put a key in at 12:00:00
when I keep getting the key from the cache within 5 seconds, the cache expiration message is never shown.
My assumption was, that the expiration was measured from the moment it was put into the cache.
so it would expire at 12:00:05
or... am I doing something wrong?

**Comment by marcelloh** [comment]
solved... Damn. I'm such a slow reader ...

cache.SkipTtlExtensionOnHit(true)

Thanks for this library

**Comment by ReneKroon** [comment]
I'm happy that this was fixable by the docs :-)
