### ISSUE TITLE
Crash recovery

### ISSUE THREAD

**Issue by jimymodi** [ReneKroon/ttlcache#22]
Is there any crash recovery mechanism implemented ?

**Comment by ReneKroon** [comment]
What is your usecase? Normally the library will not crash. If you experience crashes, please provide a way to reproduce the crashes. If you want to limit the size of the cache then maybe you can work with `Count` function or keep track of bytes during insert and on `SetExpirationCallback ` but in that case you're probably better off using a least recently used (LRU) cache from somebody else.

**Comment by jimymodi** [comment]
Actually we want to use it at multiple places. Would like to deploy this as an independent service which will be used by other services through API. The major use-cases revolve around session expiration, snoozing messages etc. The main functionality we are interested in is expiry callback.

Btw, we havn't used it, hence no experiences on crash. However crash can also happen due to external factors like machine failure and not only library crashes.

**Comment by ReneKroon** [comment]
The cache has no backing store, so is in-memory only. An approach i use is that data that is inserted into the system is written in to the DB and cache. I cannot recommend an integrated solution, some managed Redis (on Google Cloud Platform) can use a backed store, but it's expensive.
