### ISSUE TITLE
func (cache *Cache) startExpirationProcessing() - Never Exits and Leaves residual Goroutines.

### ISSUE THREAD

**Issue by zkynet** [ReneKroon/ttlcache#23]
Hey, I noticed there is no exit case in your Goroutine here:
https://github.com/ReneKroon/ttlcache/blob/49e7d8e56413a8ee1f826b064e7268f6e10ca2d3/cache.go#L52

I was developing an application that start multiple caches as child-struct. But when the parent is removed this function - func (cache *Cache) startExpirationProcessing() - keeps running forever.

Do you perhaps have a way of killing it somewhere in your code ? I like your package and I would love to keep using it, but in the current state I can not :(

**Comment by ReneKroon** [comment]
Good call, i'll fix it in the upcoming 2 weeks i think.

**Comment by zkynet** [comment]
Yep, that should do it!

However, maybe "close" is not the right description. Somehow close feels like a non-permanent move. Maybe it's just me ?

Since you already have:
NewChache()

Maybe one of these two: 
DeleteCache()
RemoveCache()

**Comment by zkynet** [comment]
Actually, now that I think about it. Do you feel like getting some help on the package ? 

I would not mind implementing a fix for you. I can make some adjustments and then deliver them in PR's.

**Comment by ReneKroon** [comment]
A pull request is always welcome. i think 'RemoveCache' is a good name but i also like to check if we can use some common standard interface. For example, Closer reads:

> type Closer
> Closer is the interface that wraps the basic Close method.
> 
> The behavior of Close after the first call is undefined. Specific implementations may document their own behavior.

```go
type Closer interface {
    Close() error
}
```

But in this case i'm happy with either solution.

**Comment by zkynet** [comment]
Yep, that makes perfect sense. I will take a look this week and see if I can't get this done :)

**Comment by ReneKroon** [comment]
@zkynet Can you test this code? Its merged to master but not an official release yet.

**Comment by zkynet** [comment]
Sweet, I was about to get my hand dirty tonight, but since you already did I'll do a testing session in stead. It'll happen in about 6-7 hours.

Good job.

**Comment by zkynet** [comment]
Completely forgot to report back! 

It seems that did it. Thanks man!
