### ISSUE TITLE
call expirationCallback automatically on cache.Close()

### ISSUE THREAD

**Issue by LihuaWu** [ReneKroon/ttlcache#28]
Is it possible to call expirationCallback on each remaining keys in the cache, when calling cache.Close()?

The purpose is to keep the overall expirationCallback behavior the same?

**Comment by LihuaWu** [comment]
@ReneKroon 
Thanks for your time.

**Comment by ReneKroon** [comment]
Good idea, will have to check the feasibility first.

**Comment by ReneKroon** [comment]
@LihuaWu can you test if this solves the issue for you? I added code to run all expiration callbacks on Close() including a test to verify this.

**Comment by LihuaWu** [comment]
I will update the result soon, Thanks

**Comment by LihuaWu** [comment]
@ReneKroon 
I have looked at the unit test, and thanks for your quick feedback.
Would it be better for  `cache.Close` to wait all expirationCallback functions executed before it returns?
Currently, it will just start a new goroutine for each expirationCallback function to execute, and thus it is not possible to know when all expirationCallback calls will be finished.

**Comment by ReneKroon** [comment]
I'd say it's a fair request, however during normal operation the expiration is async and this would imply that any items cleaned up just before calling ``cache.Close`` are still maybe executing the handler, while the synchronous callbacks are already done. This would create a race condition as it's not guaranteed that all callbacks have completed once ``cache.Close`` returns. I'd suggest using ``sync.WaitGroup`` inside the callback to keep track of callback's in progress. Would that work in your case?

**Comment by LihuaWu** [comment]
@ReneKroon  
I think you are right, and it makes sense to keep the callbacks in async.
Synchronous callbacks are only special cases for the cache.Close operation.
And keeping track of progress in the callback is a viable option for me.
Thanks!

**Comment by LihuaWu** [comment]
@ReneKroon and I have no further concerns.

**Comment by ReneKroon** [comment]
Ok, will release this officially then.
