### ISSUE TITLE
[enhancement] support for invalidate

### ISSUE THREAD

**Issue by ekovacs** [ReneKroon/ttlcache#30]
it would be amazing feature if ttlcache would additionally support invalidation of a given cache entry besides the time based expiration.
invalidation could be sync or async (depending of a boolean flag). upon invalidation, the expiration callback could be executed.

**Comment by ReneKroon** [comment]
After v2 and #31 i will have to re-evaluate this. The API call is easy, i'm not sure if the heap removal and additional sorting are easy to do.

**Comment by ReneKroon** [comment]
This was more of a bug than a feature. It's also available for testing on the v2 branch.
