### ISSUE TITLE
[enhancement] support for loader function

### ISSUE THREAD

**Issue by ekovacs** [ReneKroon/ttlcache#31]
it would be awesome, if ttlcache could be given a loader function.
Upon a cache miss (key not present in the cache), the cache would call this loader func, and create/load the value for the key, and would put it in the cache with the default global expiration.

**Comment by ReneKroon** [comment]
I'm planning a little work for a v2, consequently this would mean i can solve #29 by having an error return value on all public calls. It would then also be 'free' to add a `SetLoader` function as it can transparently relay any errors. I guess this will be done somewhere in the next 4 weeks.

**Comment by ReneKroon** [comment]
Hi, @ekovacs are you able to check how the changes on the V2 branch would work for you?
