### ISSUE TITLE
Unexported expireCallback type makes it difficult to mock the SetExpireCallback method

### ISSUE THREAD

**Issue by darkliquid** [ReneKroon/ttlcache#36]
I'm using ttlcache but want to test the behaviour of the code using it without relying on actual time passing in a reliable way, and therefore want to use a mock cache. However, I can't make an interface with a compatible `SetExpireCallback` method, because it takes a specific, unexported type `expireCallback` instead of a plain `func(string, interface{})` type.

Ideally I'd either have the `SetExpireCallback` method signature use the plain `func(string, interface{})` type for it's parameter, though a less pleasant alternative is to have the `expireCallback` type exported as `ExpireCallback` so that my interface can use it.

**Comment by ReneKroon** [comment]
Hello, is this on the 1.x versions? In version 2.1.0 this type is actually exported.
As `type ExpireCallback func(key string, value interface{})`

**Comment by darkliquid** [comment]
I totally didn't even notice there was a V2. I was just using whatever go get was pulling by default - I'll try upgrading to V2 in my go.mod
