### ISSUE TITLE
Is there any plan to add some metrics

### ISSUE THREAD

**Issue by qwding** [ReneKroon/ttlcache#37]
example: hit rate

**Comment by ReneKroon** [comment]
good call, if i do this i would be inclined to give prometheus style int64 counters, leaving you to do the math.

For example:

- Inserted
- Retrievals
- Hits
- Misses
- Evicted

would this work for you, or do you have a different proposal?

**Comment by qwding** [comment]
Great! That enough for me.Thanks

**Comment by ReneKroon** [comment]
I added these metrics, can you test it on master?

**Comment by qwding** [comment]
It looks ok. 
I have another question.
I used to use https://github.com/goburrow/cache.
Since I change the pkg to ttlcache. I found the latency increase. Estimated increase 30%。
I have not reading the code detailedly。 So want to know, is there some place waste time or some way to improve it.

**Comment by ReneKroon** [comment]
I would say it depends on your usecase. I have ~1000 items in the cache with a lifetime of a minute or two. I perform ~3K requests per second on that it's fine.

I can imagine that if you fill the cache continuously with 100K items and the lifetime is in milliseconds, together with high traffic will lead to lock contention.

Performance comes second in this cache after correctness (knowing that expiration will happen in time on all cases). I'm not planning to rework this to a sharded cache or such in the short term, where it could the contention.

If you can provide details on your specific performance issue then i can have a look though.

**Comment by ReneKroon** [comment]
I want to add that i also do not use the loader function yet, this can also be a source of delay due to a bug.

**Comment by ReneKroon** [comment]
Released in 2.2.0
