### ISSUE TITLE
Feature request: ability to know why an expiry has occurred

### ISSUE THREAD

**Issue by darkliquid** [ReneKroon/ttlcache#38]
Currently if you register an expiry callback, that callback gets called in one of 3 different scenarios:

 1. The key expires due to the TTL
 2. The key is manually removed via a call to `Remove`
 3. The cache is closed via `Close`

However, you have no way of knowing from within the expiry callback which scenario has occurred. 

For context, I have a scenario where I am maintaining a list of items that can be added and removed by users, and if they are removed by users, the cleanup process is already handled as part of handling the users request. However, items need to expire as well and in that case, the users need to be informed that their items have been removed automatically. In the current implementation, if a user removes their own items, they also get informed their item was removed automatically due to the expiration callback firing.

My proposal is for the expiration callback to take an additional argument `reason` which can be checked against to see if it was triggered by a Remove, Close or TTL expiry, which then gives me the option of handling it differently for each scenario. Alternatively, having a flag much like the `SkipTTLExtensionOnHit` such as `ExpireOnTTLOnly` to allow me to strictly support callbacks firing only expirations due to actual _expiry_ rather than removal from the cache would be useful.

**Comment by ReneKroon** [comment]
Makes sense, have to sleep on it first 😴

**Comment by ReneKroon** [comment]
i created a branch (no tests yet!) to show a straightforward change. @darkliquid Is this something that would work for you?

**Comment by darkliquid** [comment]
That looks good to me!

**Comment by ReneKroon** [comment]
The feature is released, the old function will be removed in the next major version.

**Comment by darkliquid** [comment]
Brilliant, thank you!

On February 4, 2021, Filipe Seabra <notifications@github.com> wrote:
> The feature is released, the old function will be removed in the next

> major version.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ReneKroon/ttlcache/issues/38#issuecomment-
773129559>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAHUGGENGYKADAJKS3YBR3S5JLT5ANCNFSM4WTJQZMQ>.
