### ISSUE TITLE
Export Touch function

### ISSUE THREAD

**Issue by DerkSchooltink** [ReneKroon/ttlcache#40]
By using `ttlcache.Cache#SkipTTLExtensionOnHit(bool)` you can disable touching the cache entry when using `Get`. This offers an additional level over control TTL behaviour. 

To offer even more control of this mechanism, I would like to propose to export a touch function as well:

```
func (cache *Cache) Touch(key string) error {
	cache.mutex.Lock()
	item, exists := cache.items[key]
	if !exists {
		return ErrNotFound
	}
	
	item.touch()
	cache.mutex.Unlock()
	return nil
}
```

Or something similar 😄 

This is a lot more convenient that manually getting and setting the item with a new TTL.

**Comment by ReneKroon** [comment]
Hi Derk, 

I understand this can be useful, but can you add your usecase? How would you use this functionality? I designed this expecting that you want the data with the key in order to do something useful. So if you explain how you would use it, it's probably an easy change.

Greetings,

Rene

**Comment by DerkSchooltink** [comment]
The idea is that when I want to add something to the cache, but the element with that key is already present, I instead just want to reset the TTL. 

I would say this is a valid use-case opposed to just using `Set(key, value) error` in scenarios where you're not interested in updating the value for a certain key (static key-pair values), and treat it more as an append-only cache. 

@ReneKroon if you have tips regarding my use-case I would love to hear them! This seemed like the most pragmatic approach for it, let me know if you agree. 😄
