### ISSUE TITLE
got panic

### ISSUE THREAD

**Issue by tran-wang** [ReneKroon/ttlcache#46]
panic: runtime error: index out of range [0] with length 0

```
github.com/ReneKroon/ttlcache/v2.(*Cache).SetWithTTL(0xc0001e8000, 0xc0145aa1e0, 0x20, 0x968da0, 0xc01707c480, 0xd18c2e2800, 0x0, 0x97cc40),
	/go/pkg/mod/github.com/!rene!kroon/ttlcache/v2@v2.5.0/cache.go:249 +0x3f9,
github.com/ReneKroon/ttlcache/v2.(*Cache).invokeLoader(0xc0001e8000, 0xc0145aa1e0, 0x20, 0x9f1d60, 0xc0004b4088, 0x866700, 0x96a2a0, 0xc00007a0a8),
	/go/pkg/mod/github.com/!rene!kroon/ttlcache/v2@v2.5.0/cache.go:357 +0xca,
github.com/ReneKroon/ttlcache/v2.(*Cache).GetByLoader(0xc0001e8000, 0xc0145aa1e0, 0x20, 0x0, 0x9, 0x1, 0x3, 0xc0145aa1e

```

**Comment by ReneKroon** [comment]
Thanks, do you have anymore info on this, or at least the configuration of the cache? The error occurs in a section that deals with maintaining the maximum amount of items.

**Comment by ReneKroon** [comment]
There is indeed a race condition in v2.5.0 that allows you to set the cache to zero (meaning infinite) while it's checking which element to remove, this could then lead to removal of the first item in the cache. If the cache is empty at that time it will panic. I will release v2.7.0 which solves this by adding a lock around the `SetCacheSizeLimit` call and all other configuration functions.

**Comment by tran-wang** [comment]
Sorry for the delayed reply.
It seems to have memory leak issues when store pointer, I can't find where cause memory leak.
This project is really complex, so I implemented [a very simple Cache](https://gist.github.com/tran-wang/4e9c476ebef025d85912c2a1383432da) using sync.Map, and fixed my problem.
