### ISSUE TITLE
this library eating CPU time even when idle (not accessed)

### ISSUE THREAD

**Issue by kokizzu** [ReneKroon/ttlcache#48]
doing 30s profiling, it eats 36s of CPU time..
![image](https://user-images.githubusercontent.com/1061610/122587370-f684e900-d087-11eb-8a77-f5a4600dd30f.png)
using [gops/pprof-cpu](http://kokizzu.blogspot.com/2021/01/gops-trace-your-golang-service-with-ease.html)

**Comment by kokizzu** [comment]
for that 14.83s part, probably replacing with https://github.com/kpango/fastime works
for the selectgo part probably there's `select` channel but with `default` (it would eat CPU time)

**Comment by ReneKroon** [comment]
OK, will check this out. Definitely hasn't received attention so far

**Comment by ReneKroon** [comment]
Are you running with a very low TTL ? I find 'meaningful' cpu usage for example if the global TTL is set to 1 milisecond. It would be nice to know your configuration and usage pattern.

**Comment by kokizzu** [comment]
I'm using 30s-90s TTL
only calling `SetExpirationReasonCallback`, the rest are default

**Comment by ReneKroon** [comment]
When checking one of my production services that does 1-3 cache lookups per REST request, and then some queries, i don't see significant usage. When i create a synthetic case with `SetExpirationReasonCallback` i do see some usage. However the time spent is in a different part than you show.

I'm using Go 1.16 and latest version of the library on Darwin. Is your deployment also on latest versions?
![Screenshot 2021-06-23 at 21 00 08](https://user-images.githubusercontent.com/3002872/123153604-22c4af00-d466-11eb-9fb4-54720ebced3e.png)

Bench:
```go
package main

import (
	"fmt"
	"log"
	"math/rand"
	"os"
	"runtime"
	"runtime/pprof"
	"time"

	"github.com/ReneKroon/ttlcache/v2"
)

var notFound = ttlcache.ErrNotFound

func main() {
	cache := ttlcache.NewCache()
	cache.SetExpirationReasonCallback(func(key string, reason ttlcache.EvictionReason, value interface{}) {
		if key == value {
			reason = 0
		}
	})
	f, err := os.Create("barf.pprof")
	if err != nil {
		log.Fatal(err)
	}
	pprof.StartCPUProfile(f)
	defer pprof.StopCPUProfile()

	cache.SetTTL(time.Second * 3)

	for j := 1; j < 30; j++ {
		for i := 1; i < 10000; i++ {

			cache.SetWithTTL(fmt.Sprintf("%d", i), "MyValue", time.Millisecond*time.Duration(rand.Int31n(10)))
			cache.Set("MyNumber", 1000)

			if val, err := cache.Get(fmt.Sprintf("%d", i)); err != notFound {
				a := val
				if a == "ADF" {

				}
			}

		}
		time.Sleep(time.Millisecond * 10)
	}

	cache.Purge()

	cache.Close()
}
```

**Comment by ReneKroon** [comment]
I think you were looking at the 'blocking' profile instead of cpu profile?
