### ISSUE TITLE
Cache Never Expires Over Certain TTL Value

### ISSUE THREAD

**Issue by ztroop** [ReneKroon/ttlcache#52]
I noticed while playing with this module that I can specify a TTL value from `10` to `50` seconds and everything works great!
However, if I specify a TTL value like `300`, the cache never seems to expire. Apologies of I'm missing something simple here!

Code Snippet:

```
cache := ttlcache.NewCache()
ttl, err := strconv.Atoi(cacheTTL)
if err != nil {
    log.Fatal("Invalid TTL value: ", err)
}
cache.SetTTL(time.Duration(ttl) * time.Second)

expirationCallback := func(key string, _ ttlcache.EvictionReason, _ interface{}) {
    log.Info("Cache expired for key: ", key)
}
cache.SetExpirationReasonCallback(expirationCallback)
```

**Comment by ztroop** [comment]
That appears to be what I needed, thanks for steering me in the right direction.

**Comment by ReneKroon** [comment]
Happy to see some community interaction! PROPS TO YOU, @jspri, once again.
