### ISSUE TITLE
Feature request: Add option to set how many "oldest items" should be purged when the cache limit is reached

### ISSUE THREAD

**Issue by toastyblast** [ReneKroon/ttlcache#61]
From what I can tell, if upon calling a `cache.Set(...)` with an item not already in the cache, but the cache is at the configured limit (e.g. 100), only the single oldest item (closest to reaching its TTL) is removed.

Could there be an option we can set on the cache, controlling the amount of items that are removed whenever a `cache.Set(...)` is called that would add a new item over the limit?
E.g. if the limit is set to 1000, we're adding an item #1001, and then instead of just deleting 1 item, we can set it to removing the oldest 100 items, reducing the cache back to 901 current items. 

I think this would be more efficient, especially for environments where there are a lot of unique items, but most appear rarely, so the oldest items in the cache don't matter as much and can safely be deleted at any time the limit is reached, in one batch.

**Comment by ReneKroon** [comment]
I ran some benchmarks with cache removals of 1, 10 and 100. It seems there's not much effect:

removal of 1
```
pkg: github.com/ReneKroon/ttlcache/v2/bench
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkCacheSetWithLimit-12        1837465           634.6 ns/op       104 B/op          3 allocs/op
PASS
```

removal of 10
```
pkg: github.com/ReneKroon/ttlcache/v2/bench
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkCacheSetWithLimit-12        1863397           646.4 ns/op       103 B/op          3 allocs/op
PASS
```

removal of 100

```
pkg: github.com/ReneKroon/ttlcache/v2/bench
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkCacheSetWithLimit-12        1925269           619.9 ns/op       105 B/op          3 allocs/op
PASS
```

**Comment by ReneKroon** [comment]
I also don't see much opportunity to create a batch operation since a map has to be changed during the eviction process. No locking operations are saved if a batch removal would exists. Therefore leaving as-is seems to be a good option.
