### ISSUE TITLE
Export / Import functionality 

### ISSUE THREAD

**Issue by thisisdev-patrick** [ReneKroon/ttlcache#67]
I'm trying to move away from patrickmn cache usage in my projects. And I'd like to implement yours where needed. I miss an export and import cache function to persist cache between runs in your cache. Can I add this as a feature request? If you don't have the time and like the idea, I'm willing to help also. 

Thanks in advance

**Comment by ReneKroon** [comment]
so `GetItems` was recently added and this should make the MVP possible. What extra functionality do you need for your scenario?

**Comment by thisisdev-patrick** [comment]
hm, I think I already can implement it with your custom loader function. I'll give it a shot after X-mas and let you know, for now you can close this issue... Thanks for the prompt response! :P
