### ISSUE TITLE
add a getter function which gets a value, if it's not in the cache

### ISSUE THREAD

**Issue by sclausen** [ReneKroon/ttlcache#8]
It would be handy, if you could provide a getter function for the cache to retrieve actually retrieve the content, if the cache doesn't contain the requested value like in googles LoadingCache.

**Comment by ReneKroon** [comment]
Closing this since it won't be implemented. I guess wrapping the cache in a new struct that does loading of missing values is a solution. I decide to do this since the complexity of the cache is quite high and therefore i'd like to keep it focused on just that.
